EngineTrendMonitoring/EngineTrendMonitoring.Web/Models/ErrorViewModel.cs
namespace EngineTrendMonitoring.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EngineTrendMonitoring/EngineTrendMonitoring.Web/Controllers/Aircraft/AircraftController.cs
using Microsoft.AspNetCore.Mvc;

namespace EngineTrendMonitoring.Web.Controllers.Aircraft
{
    public class AircraftController : Controller
    {
        #region Properties
        #endregion

        #region Constructor
        #endregion

        #region GET - Index
        public IActionResult Index()
        {
            return View();
        }
        #endregion

        #region POST - Get
        #endregion

        #region GET - Create
        #endregion

        #region POST - Create
        #endregion

        #region GET - Edit
        #endregion

        #region POST - Edit
        #endregion

        #region POST - Delete
        #endregion
    }
}

EngineTrendMonitoring/EngineTrendMonitoring.Web/Controllers/EngineTrend/EngineTrendController.cs
using Microsoft.AspNetCore.Mvc;

namespace EngineTrendMonitoring.Web.Controllers.EngineTrend
{
    public class EngineTrendController : Controller
    {
        #region Properties
        #endregion

        #region Constructor
        #endregion

        #region GET - Index
        public IActionResult Index()
        {
            return View();
        }
        #endregion

        #region POST - Get
        #endregion

        #region GET - Create
        #endregion

        #region POST - Create
        #endregion

        #region GET - Edit
        #endregion

        #region POST - Edit
        #endregion

        #region POST - Delete
        #endregion
    }
}

EngineTrendMonitoring/EngineTrendMonitoring.Web/Controllers/Home/HomeController.cs
using EngineTrendMonitoring.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EngineTrendMonitoring.Web.Controllers.Home
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EngineTrendMonitoring/EngineTrendMonitoring.Web/Controllers/HomeController.cs
using EngineTrendMonitoring.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EngineTrendMonitoring.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EngineTrendMonitoring/EngineTrendMonitoring.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row row-cols-1 row-cols-lg-2 align-items-center justify-content-between border-bottom g-1 my-3">
    <h3 class="fs-2 mb-2">Dashboard</h3>

    <div class="row align-items-center gx-2">
        <div class="col-12 col-lg-4 mb-2">
            <div class="form-floating">
                <select class="form-select" id="Aircraft">
                    <option value=""></option>
                </select>
                <label for="Aircraft">Aircraft</label>
            </div>
        </div>

        <div class="col-6 col-lg-4 mb-2">
            <div class="form-floating">
                <input type="date" class="form-control" id="DateFrom" />
                <label for="DateFrom">From</label>
            </div>
        </div>

        <div class="col-6 col-lg-4 mb-2">
            <div class="form-floating">
                <input type="date" class="form-control" id="DateTo" />
                <label for="DateFrom">To</label>
            </div>
        </div>
    </div>
</div>

<div class="accordion" id="accordionCharts">
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTailVolumeChart" aria-expanded="true" aria-controls="collapseTailVolumeChart">
                Tail Volume
            </button>
        </h2>

        <div id="collapseTailVolumeChart" class="accordion-collapse collapse show" data-bs-parent="#accordionCharts">
            <div class="accordion-body">

                <div class="card">
                    <div class="card-body">
                        <canvas id="tailVolumeChart"></canvas>
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-sm table-striped">
                                <thead class="bg-primary-subtle">
                                    <tr>
                                        <th class="text-center">Aircraft</th>
                                        <th class="text-center">Collection Date</th>
                                        <th class="text-center">Tail Volume</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="text-center">Sample</td>
                                        <td class="text-center">06/22/2024</td>
                                        <td class="text-center">1500</td>
                                    </tr>
                                    <tr>
                                        <td class="text-center">Sample</td>
                                        <td class="text-center">06/21/2024</td>
                                        <td class="text-center">500</td>
                                    </tr>
                                    <tr>
                                        <td class="text-center">Sample</td>
                                        <td class="text-center">06/20/2024</td>
                                        <td class="text-center">700</td>
                                    </tr>
                                    <tr>
                                        <td class="text-center">Sample</td>
                                        <td class="text-center">06/19/2024</td>
                                        <td class="text-center">900</td>
                                    </tr>
                                    <tr>
                                        <td class="text-center">Sample</td>
                                        <td class="text-center">06/18/2024</td>
                                        <td class="text-center">1100</td>
                                    </tr>
                                    <tr>
                                        <td class="text-center">Sample</td>
                                        <td class="text-center">06/17/2024</td>
                                        <td class="text-center">1300</td>
                                    </tr>
                                    <tr>
                                        <td class="text-center">Sample</td>
                                        <td class="text-center">06/16/2024</td>
                                        <td class="text-center">1500</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFlightHoursChart" aria-expanded="false" aria-controls="collapseFlightHoursChart">
                Flight Hours & Cycles
            </button>
        </h2>

        <div id="collapseFlightHoursChart" class="accordion-collapse collapse" data-bs-parent="#accordionCharts">
            <div class="accordion-body">

                <div class="card">
                    <div class="card-body">
                        <canvas id="flightHoursChart"></canvas>
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-sm table-striped">
                                <thead class="bg-primary-subtle">
                                    <tr>
                                        <th class="text-center">Aircraft</th>
                                        <th class="text-center">Collection Date</th>
                                        <th class="text-center">Flight Hours</th>
                                        <th class="text-center">Flight Cycles</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOutsideInfoChart" aria-expanded="false" aria-controls="collapseOutsideInfoChart">
                Outside Info (Air Temperature, Altitude and Airspeed)
            </button>
        </h2>

        <div id="collapseOutsideInfoChart" class="accordion-collapse collapse" data-bs-parent="#accordionCharts">
            <div class="accordion-body">

                <div class="card">
                    <div class="card-body">
                        <canvas id="outsideInfoChart"></canvas>
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-sm table-striped">
                                <thead class="bg-primary-subtle">
                                    <tr>
                                        <th class="text-center">Aircraft</th>
                                        <th class="text-center">Collection Date</th>
                                        <th class="text-center">OAT</th>
                                        <th class="text-center">Altitude</th>
                                        <th class="text-center">Airspeed</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/chart.js/dist/chart.umd.min.js" asp-append-version="true"></script>
    <script src="~/Views/Home/Index.cshtml.js" asp-append-version="true"></script>
}

EngineTrendMonitoring/EngineTrendMonitoring.Web/Views/Shared/_Layout.cshtml
@{ 
    const string ApplicationName = "Engine Trend Monitoring";
}

<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @ApplicationName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EngineTrendMonitoring.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="navbar navbar-expand-lg sticky-top border-bottom bg-body-tertiary">
        <nav class="container-xxl flex-wrap flex-lg-nowrap pt-1 pt-lg-0 px-3">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <h5>@ApplicationName</h5>
            </a>

            <button type="button" class="navbar-toggler d-lg-none" data-bs-toggle="offcanvas" data-bs-target="#navbarOffcanvas">
                <i class="bi bi-three-dots"></i>
            </button>

            <div class="offcanvas-lg offcanvas-end flex-grow-1" tabindex="-1" id="navbarOffcanvas" data-bs-scroll="true">
                <div class="offcanvas-header pb-0">
                    <h5 class="offcanvas-title">@ApplicationName</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#navbarOffcanvas"></button>
                </div>

                <div class="offcanvas-body pt-0">
                    <hr class="d-lg-none" />

                    <ul class="navbar-nav flex-row flex-wrap">
                        <li class="nav-item col-6 col-lg-auto">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Dashboard</a>
                        </li>

                        <li class="nav-item col-6 col-lg-auto">
                            <a class="nav-link" asp-controller="Aircraft" asp-action="Index">Aircraft</a>
                        </li>

                        <li class="nav-item col-6 col-lg-auto">
                            <a class="nav-link" asp-controller="EngineTrend" asp-action="Index">Engine Trend</a>
                        </li>
                    </ul>

                    <hr class="d-lg-none" />

                    <ul class="navbar-nav flex-row flex-wrap ms-md-auto">
                        <li class="nav-item col-6 col-lg-auto">
                            <a class="nav-link" href="https://github.com/fernandokeller/EngineTrendMonitoring" target="_blank">
                                <i class="bi bi-github"></i>
                                <span class="d-lg-none ms-2">GitHub</span>
                            </a>
                        </li>

                        <li class="nav-item col-12 col-lg-auto">
                            <div class="vr d-none d-lg-flex h-100 mx-lg-2"></div>
                            <hr class="d-lg-none my-2">
                        </li>

                        <li class="nav-item dropdown">
                            <button class="btn btn-link nav-link dropdown-toggle" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" data-bs-display="static">
                                <i class="bi bi-circle-half"></i>
                                <span class="ms-2 d-lg-none">Theme</span>
                            </button>

                            <ul class="dropdown-menu dropdown-menu-end">
                                <li>
                                    <button type="button" class="dropdown-item" data-bs-theme-value="light">
                                        <i class="bi bi-sun-fill me-2"></i>
                                        Light
                                    </button>
                                </li>

                                <li>
                                    <button type="button" class="dropdown-item" data-bs-theme-value="dark">
                                        <i class="bi bi-moon-stars-fill me-2"></i>
                                        Dark
                                    </button>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="position-fixed w-100 bottom-0 border-top bg-body-tertiary">
        <div class="container text-body-secondary text-center">
            <a class="text-body-emphasis text-decoration-none" asp-controller="Home" asp-action="Index">
                <span class="fs-5">&copy; @DateTime.Today.Year @ApplicationName</span>
            </a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/theme.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>